version: "3.0"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - PGUSER=emx2
      - POSTGRES_USER=emx2
      - POSTGRES_PASSWORD=emx2
      - POSTGRES_DB=emx2
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
#  emx2:
#    image: mswertz/emx2
#    command: -DMOLGENIS_POSTGRES_URI=jdbc:postgresql://postgres/molgenis
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    restart: on-failure

